site_name: The Quantum Abstract Machine - QuAM Documentation
# site_url: 
site_author: QM. Technologies Ltd.
# site_description:

copyright: Copyright &copy; 2024 Q.M Technologies Ltd.

theme:
  name: material
  logo: assets/qm_logo_white.svg
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/qm_logo_white.svg
  palette:
    - scheme: entropy-bright
      toggle:
        icon: material/brightness-7
        name: Switch to high contrast mode
    - scheme: entropy-high-contrast
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - scheme: entropy-dark 
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

  features:
  # - navigation.tabs  # Add tabs to the top of the page
  # - navigation.sections  # Expand sections in the navigation
  - navigation.top # Add "back to top" button when scrolling back up
  - toc.integrate  # Invlude TOC in left sidebar instead of separate right
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotations
  - content.code.copy
  language: en

extra_css:
  - stylesheets/extra.css

nav:
  - index.md
  - getting-started.md
  - migrating-to-quam.md
  - demonstration.md
  - "QuAM features":
    - quam-references.md
  - "QuAM components":
    - "components/channels.md"
    - "components/pulses.md"
    - "components/octave.md"
    - custom-components.md

plugins:
# - mkdocs-jupyter:
#     include:
#       - "*.ipynb"
- search
- autorefs  # Automatically link across pages
- gen-files:  # Autogenerate code reference using mkdocstrings
    scripts:
    - docs/gen_ref_pages.py
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [quam]

markdown_extensions:
  - pymdownx.blocks.tab:  # Add tabs to markdown using: === "title"
      alternate_style: true  # Somehow this is required for tabs to work
  - pymdownx.blocks.details  # Enable collapsible elements, e.g.: ??? tip "title"
  - pymdownx.superfences  # Enable multiline code in tabs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg