name: Build python package
on:
  workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"


      - name: Install python deps
        run: python -m pip install -e .[build]

      - name: Build python package
        run: python -m build

      - uses: actions/upload-artifact@v4
        id: upload-sdist
        name: Upload sdist
        with:
          name: python-package-sdist
          path: dist/quam-*.tar.gz
          retention-days: 3
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        id: upload-wheel
        name: Upload wheel
        with:
          name: python-package-wheel
          path: dist/quam-*.whl
          retention-days: 3
          if-no-files-found: error
